# Generated by Django 3.1.2 on 2020-11-24 00:28

from django.db import migrations, models
from django_mysql.models import ListTextField
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('courses', '0001_initial'),
        ('participants', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_session', models.TextField(choices=[('2019-2020', 'Session 1920'), ('2020-2021', 'Session 2021'), ('2021-2022', 'Session 2122'), ('2022-2023', 'Session 2223'), ('2023-2024', 'Session 2324')], null=True)),
                ('term', models.TextField(null=True)),
                ('event_type', models.TextField(choices=[('CLINIC', 'Clinic'), ('ASSESSNEBT', 'Assessment'), ('CLINIC_ACTIVITY', 'Clinic_activity'), ('CLINIC_ASSESSMENT', 'Clinic_assessment'), ('LAB', 'Lab'), ('LAB_ASSESSMENT', 'Lab_assessment'), ('LECTURE', 'Lecture'), ('ORIENTATION', 'Orientation'), ('REMEDIAL', 'Remedial'), ('SEMINAR', 'Seminar'), ('SIM_CLINIC', 'Sim_clinic'), ('SIM_LAB', 'Sim_lab')],null=True)),
                ('event_title', models.TextField(null=True)),
                ('event_objectives', ListTextField(base_field= models.CharField(max_length = 1000),null=True)),
                ('event_desc', models.TextField(null=True)),
                ('event_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('total_duration', models.IntegerField(null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='courses.course',null=True)),
                ('prog_id', models.ForeignKey(db_column='prog_id', on_delete=django.db.models.deletion.PROTECT,
                                                to='programs.program', null=True)),
                ('discipline_domain', ListTextField(base_field= models.CharField(max_length = 1000),null=True)),
                ('location', models.TextField(null=True)),
                ('course_director', models.TextField(null=True)),
                ('instructors', ListTextField(base_field= models.CharField(max_length = 1000),blank=True, null=True)),
                ('session_plan', models.TextField(blank=True, null=True)),
                ('number_of_students', models.IntegerField(null=True)),
                ('assistant_operator', models.TextField(blank=True, null=True)),
                ('clinic_sim_lab_equipment', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cal_event',
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('event_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(max_length=120, null=True)),
                ('vodcast_url', models.TextField(max_length=120, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='groups.group', null=True)),
            ],
            options={
                'db_table': 'cal_event_group',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(max_length=120)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cal_tag',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('event_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('tag_id', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='events.tag')),
            ],
            options={
                'db_table': 'cal_event_tag',
            },
        ),
        migrations.CreateModel(
            name='EventGroupInstructor',
            fields=[
                ('event_group_instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('event_group_id', models.ForeignKey(db_column='event_group_id', on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup')),
                ('instructor_id', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='participants.participant', null=True)),
            ],
            options={
                'db_table': 'cal_event_group_instructor',
            },
        ),
        migrations.CreateModel(
            name='EventFileAttachment',
            fields=[
                ('event_file_attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('event_file_name', models.TextField()),
                ('event_file_desc', models.TextField(null=True)),
                ('event_file_link', models.TextField(null=True)),

            ],
            options={
                 'db_table': 'cal_event_file_attachment',
            },
        ),
        migrations.CreateModel(
            name='EventInstructorFileAttachment',
            fields=[
                ('event_instructor_file_attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('event_instructor_file_name', models.TextField()),
                ('event_instructor_file_desc', models.TextField(null=True)),
                ('event_instructor_file_link', models.TextField(null=True)),

            ],
            options={
                 'db_table': 'cal_event_instructor_file_attachment',
            },
        ),
        migrations.CreateModel(
            name='EventVodcast',
            fields=[
                  ('event_vodcast_id', models.AutoField(primary_key=True, serialize=False)),
                  ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                  ('vodcast_url', models.TextField()),
            ],
            options={
                         'db_table': 'cal_event_vodcast',
                    },
            )

    ]