# Generated by Django 3.1.2 on 2021-08-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.TextField(choices=[('CLINIC', 'Clinic'), ('ASSESSMENT', 'Assessment'), ('CLINIC ACTIVITY', 'Clinic Activity'), ('CLINIC ASSESSMENT', 'Clinic Assessment'), ('LAB', 'Lab'), ('LAB ASSESSMENT', 'Lab Assessment'), ('LECTURE', 'Lecture'), ('ORIENTATION', 'Orientation'), ('REMEDIAL', 'Remedial'), ('SEMINAR', 'Seminar'), ('SIM CLINIC', 'Sim Clinic'), ('SIM LAB', 'Sim Lab')], null=True),
        ),
        migrations.AlterField(
            model_name='eventfileattachment',
            name='event_file_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventfileattachment',
            name='event_file_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventfileattachment',
            name='event_file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinstructorfileattachment',
            name='event_instructor_file_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinstructorfileattachment',
            name='event_instructor_file_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinstructorfileattachment',
            name='event_instructor_file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_title', models.TextField(max_length=50)),
                ('passcode', models.TextField(max_length=10)),
                ('meeting_url', models.URLField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
