# Generated by Django 4.0.2 on 2022-02-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('events', '0002_auto_20210814_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course_id',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
