# Generated by Django 3.1.2 on 2020-11-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id',models.AutoField(primary_key=True)),
                ('participant_ccid', models.CharField(max_length=120)),
                ('participant_type', models.TextField(choices=[('Instructor', 'Instructor'), ('Student', 'Student'), ('Admin', 'Admin')], null=True)),
                ('first', models.TextField(max_length=120, null=True)),
                ('last', models.TextField(max_length=120, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cal_participant',
            },
        ),
    ]
