# Generated by Django 4.0.2 on 2022-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
