# Generated by Django 3.1.2 on 2020-11-23 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.TextField(null=True, choices=[('DMED 511', 'Dmed 511'), ('DMED 513', 'Dmed 513'), ('DMED 515', 'Dmed 515'), ('DMED 516', 'Dmed 516')])),
                ('course_name', models.TextField(choices=[('Foundations of Medicine and Dentistry', 'Dmed 511'), ('Endocrine System', 'Dmed 513'), ('Cardiovascular System', 'Dmed 515'), ('Pulmonary System', 'Dmed 516')])),
                ('course_objectives', models.TextField(max_length=120, null=True)),
                ('course_overview', models.TextField(max_length=120, null=True)),
                ('course_director',
                 models.ForeignKey(null=True, db_column='course_director', on_delete=django.db.models.deletion.PROTECT,
                                   to='participants.participant')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cal_course',
            },
        ),
        migrations.CreateModel(
            name='CourseParticipant',
            fields=[
                ('course_participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('participant_id', models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
            options={
                'db_table': 'cal_course_participant',
            },
        ),
    ]
